### ISSUE TITLE
Fehlt auf Website!

### ISSUE THREAD

**Issue by L3P3** [LFF5644/site-minecraftServerInfo#1]
Wenn man lff.one öffnet, ist da kein Link zu diesem Projekt!

**Comment by LFF5644** [comment]
fake news

**Comment by L3P3** [comment]
*fake

**Comment by L3P3** [comment]
Doch stimmt! Da ist kein Link dazu!

**Comment by LFF5644** [comment]
doch in der readme als überschrieft wer lesen kann ist klar im vorteil 

ps. ich kann lesen aber nicht schreiben xD

**Comment by L3P3** [comment]
DIE README SIEHT KEINER DER lff.one BESUCHT MF

**Comment by L3P3** [comment]
Du kannst NICHT lesen!
